### PR TITLE
Cross-platform support

### PR DESCRIPTION
**Pull request by stevennic22**
Removed caption.sh in favor of caption.py. This opens the door for cross-platform usage and logging what  files were manipulated and moved and how.

readme.md has updated to reflect this change.

### CODE REVIEW

**Comment by tjnicolaides** [comment]
Thanks for doing this. I will test and merge this weekend, hopefully

**Comment by tjnicolaides** [comment]
I ran into this when I ran the `pip install Pillow` command, and it prevented me from testing the script any further. I will come back to check out why I got this error, but posting it here in the meantime in case it was something you encountered @stevennic22:

`  Failed building wheel for pillow
Failed to build pillow
Installing collected packages: pillow
  Running setup.py install for pillow
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;**file**='/private/var/folders/ml/2z3l83bn0p9cvxxdd3r5glhw0000gn/T/pip-build-gpdavJ/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/ml/2z3l83bn0p9cvxxdd3r5glhw0000gn/T/pip-Ea_X97-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'Pillow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'build_children.sh'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'Pillow.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/ml/2z3l83bn0p9cvxxdd3r5glhw0000gn/T/pip-build-gpdavJ/pillow/setup.py", line 753, in <module>
    zip_safe=not debug_build(), )
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/private/var/folders/ml/2z3l83bn0p9cvxxdd3r5glhw0000gn/T/pip-build-gpdavJ/pillow/setup.py", line 521, in build_extensions
    ' using --disable-%s, aborting' % (f, f))
ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

----------------------------------------
```

Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;**file**='/private/var/folders/ml/2z3l83bn0p9cvxxdd3r5glhw0000gn/T/pip-build-gpdavJ/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/ml/2z3l83bn0p9cvxxdd3r5glhw0000gn/T/pip-Ea_X97-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ml/2z3l83bn0p9cvxxdd3r5glhw0000gn/T/pip-build-gpdavJ/pillow
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by stevennic22** [comment]
I encountered a completely different error on Windows, but that was due to an odd installation of Python (originally downloaded from Ninite instead of Python directly). An update to my version of Python resolved that.

The final line there mentions upgrading pip, which may help resolve it.

`You should consider upgrading via the 'pip install --upgrade pip' command.`

You would also be able to check if you have the PIL module installed (unlikely): `pip list`
Having PIL and Pillow installed at the same time is not recommended.

**Comment by stevennic22** [comment]
Also, I have to sudo to install python modules on Debian. Maybe `sudo pip install Pillow` ?

http://stackoverflow.com/questions/36563613/python-pillow-not-installing-under-osx

Above link is related to the zlib section at the bottom of the error.

**Pull request merged**
